package com.zhph.mapper.sys;

import com.zhph.model.sys.SysRoles;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysRolesMapper {
	/**
	 * 根据角色编码和者角色名称查询
	 *
	 * @param map
	 * @return
	 */
	public List<SysRoles> selectByRoleCodeAndRoleName(Map<String, String> map);

	/**
	 * 根据用户Id查询 拥有的角色
	 * 
	 * @param userId
	 * @return
	 */
	public List<SysRoles> selectRolesByUserId(@Param("userId") String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_ROLES
	 *
	 * @mbg.generated Thu Aug 17 11:16:23 CST 2017
	 */
	public int deleteByPrimaryKey(Long roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_ROLES
	 *
	 * @mbg.generated Thu Aug 17 11:16:23 CST 2017
	 */
	public int insert(SysRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_ROLES
	 *
	 * @mbg.generated Thu Aug 17 11:16:23 CST 2017
	 */
	public int insertSelective(SysRoles record);

	/**
	 * 将角色、资源进行关联
	 * 
	 * @param resourcesId
	 * @return
	 */
	public int insertRoleAndResource(@Param("resourcesId") String resourcesId);

	/**
	 * 将角色、资源进行关联
	 * 
	 * @param roleId
	 * @param resourcesId
	 * @return
	 */
	public int updateRoleAndResource(@Param("roleId") Long roleId, @Param("resourcesId") String resourcesId);

	/**
	 * 根据roleId删除资源
	 * 
	 * @param roleId
	 * @return
	 */
	public int delResourceByRoleId(@Param("roleId") Long roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_ROLES
	 *
	 * @mbg.generated Thu Aug 17 11:16:23 CST 2017
	 */
	public SysRoles selectByPrimaryKey(Long roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_ROLES
	 *
	 * @mbg.generated Thu Aug 17 11:16:23 CST 2017
	 */
	public int updateByPrimaryKeySelective(SysRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_ROLES
	 *
	 * @mbg.generated Thu Aug 17 11:16:23 CST 2017
	 */
	public int updateByPrimaryKey(SysRoles record);

	/**
	 * 根据角色 roleId查询 对应的节点id集合
	 * 
	 * @param roleId
	 * @return
	 */
	public List<Long> selectNodeIds(@Param("roleId") Long roleId);

	public List<SysRoles> queryAllRoles();

	public void unGrantRolesByUserId(String userId);

	public void grantRoleToUser(Map<String, Object> param);
}